spring:
  profiles:
    active: local
  application:
    name: note-workbench
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  ai:
    model:
      chat: none
      embedding: none
      image: none
      moderation: none
      audio:
        speech: none
        transcription: none
#  flyway:
#    baseline-on-migrate: true
#    baseline-version: '0.1'

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
app:
  storage:
    root: ./storage
